/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2022-06-28 08:50:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>注册页面</title>\r\n");
      out.write("<style>\r\n");
      out.write(" .btn {\r\n");
      out.write("     background-color: #4CAF50;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 10px 14px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 4px 2px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write(" #btn2 {\r\n");
      out.write("  background-color: red;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image:url(images/background.jpg)\">\r\n");
      out.write("\t<form action=\"register\" method=\"get\" style=\"color:white\">\r\n");
      out.write("\t\t<label for=\"username\">姓名:</label>\r\n");
      out.write("\t\t<input type=\"text\" id=\"username\" name=\"username\" />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label for=\"password\">密码:</label>\r\n");
      out.write("\t\t<input type=\"password\" id=\"password\" name=\"password\" />\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<input type=\"radio\" id=\"sex1\" name=\"sex\" value=\"0\">\r\n");
      out.write("\t\t<label for=\"sex1\">男</label>\r\n");
      out.write("\t\t<input type=\"radio\" id=\"sex2\" name=\"sex\" value=\"1\">\r\n");
      out.write("\t\t<label for=\"sex2\">女</label>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label for=\"major\">专业</label>\r\n");
      out.write("\t\t<select id=\"major\" name=\"major\">\r\n");
      out.write("\t\t\t<option value=\"\">-</option>\r\n");
      out.write("\t\t\t<option value=\"0\">计算机</option>\r\n");
      out.write("\t\t\t<option value=\"1\">英语</option>\r\n");
      out.write("\t\t\t<option value=\"2\">数学</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<input type=\"checkbox\" id=\"hobby1\" name=\"hobby\" value=\"0\" />\r\n");
      out.write("\t\t<label for=\"hobby1\">足球</label>\r\n");
      out.write("\t\t<input type=\"checkbox\" id=\"hobby2\" name=\"hobby\" value=\"1\" />\r\n");
      out.write("\t\t<label for=\"hobby2\">篮球</label>\r\n");
      out.write("\t\t<input type=\"checkbox\" id=\"hobby3\" name=\"hobby\" value=\"2\" />\r\n");
      out.write("\t\t<label for=\"hobby3\">网球</label>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<textarea name=\"intro\">abcd</textarea>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"提交\" class=\"btn\"/>\r\n");
      out.write("\t\t<input type=\"reset\" value=\"重置\" class=\"btn\" id=\"btn2\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
